version: '3'

services:
#  postgres:
#    image: 'postgres:10.3-alpine'
#    volumes:
#      - 'postgres:/var/lib/postgresql/data'
#    env_file:
#      - '.env'

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'

  website:
    depends_on:
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  departure:
    build: .
    command: puma
    ports:
      - '4000:4000'
    volumes:
      - '.:/app/services/departure'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

volumes:
  redis:
  postgres:
